name: Deploy v2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # JDK ì„¤ì¹˜
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Jar íŒŒì¼ ë¹Œë“œ
      - name: Build JAR
        run: |
          chmod +x gradlew  # Gradle ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
          ./gradlew clean build -x test  # í…ŒìŠ¤íŠ¸ ì œì™¸

      # ë„ì»¤ ì´ë¯¸ì§€ ë¹Œë“œ
      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t naaadang/blog-app-v2:latest .
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push naaadang/blog-app-v2:latest

      # SSH í‚¤
      - name: ğŸ› ï¸ Save SSH Key and Set Permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -al ~/.ssh  # ë””ë²„ê¹…ìš©

      # EC2ì— ë°°í¬(SSH ì ‘ì†)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo "EC2 ì ‘ì† ì„±ê³µ!"
            cd ~/v2
            docker-compose down
            docker pull naaadang/blog-app-v2:latest
            docker-compose up -d 
            docker image prune -f
            docker ps